spring.application.name=savo_noru
server.port=8080

spring.datasource.url=jdbc:sqlserver://savonoru.database.windows.net:1433;database=savonoru;encrypt=true;trustServerCertificate=true;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=admin_user
spring.datasource.password=b@lkonas404
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

